# Change these first
owner: titho85 # Your GitHub organization or username, where this repository lives
repo: ozg-status # The name of this repository
assignees:
  - titho85

sites:
  - name: Service-Portal Hannover
    url: https://serviceportal.hannover-stadt.de
    icon: https://serviceportal.hannover-stadt.de/favicon.ico
    __dangerous__body_down_if_text_missing: "Service-Portal der Landeshauptstadt Hannover"
  - name: FormularService Hannover
    url: https://forms.hannover-stadt.de/intelliform/forms/lhh_ozg/index
    icon: https://serviceportal.hannover-stadt.de/favicon.ico
  - name: Virtuelles Bauamt Hannover
    url: https://ebgv.hannover-stadt.de/intelliform/sign-in?form=true
    icon: https://serviceportal.hannover-stadt.de/favicon.ico
  - name: Terminbuchung Bürgerämter Hannover
    url: https://termin.hannover-stadt.de/buergeramt
    icon: https://serviceportal.hannover-stadt.de/favicon.ico
  - name: Terminbuchung KFZ-Zulassung Hannover
    url: https://termin.hannover-stadt.de/kfz
    icon: https://serviceportal.hannover-stadt.de/favicon.ico
  - name: Terminbuchung Fahrerlaubnisbehörde Hannover
    url: https://termin.hannover-stadt.de/fahrerlaubnis
    icon: https://serviceportal.hannover-stadt.de/favicon.ico
  - name: Terminbuchung Standesamt Hannover
    url: https://termin.hannover-stadt.de/standesamt
    icon: https://serviceportal.hannover-stadt.de/favicon.ico
  - name: Terminbuchung Gewerbewesen Hannover
    url: https://termin.hannover-stadt.de/gewerbe
    icon: https://serviceportal.hannover-stadt.de/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: serviceportal.hannover-stadt.de
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/titho85/ozg-status/master/static/img/logo.png
  name: Status des Service-Portals der Landeshauptstadt Hannover
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: https://serviceportal.hannover-stadt.de/status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Service-Portal
      href: https://serviceportal.hannover-stadt.de
  favicon: https://serviceportal.hannover-stadt.de/favicon.ico
  metaTags:
    - name: "robots"
      content: "noindex"

i18n:
  activeIncidents: Aktive Störungen
  allSystemsOperational: Alle Systeme sind verfügbar
  incidentReport: "Ticket #$NUMBER Übersicht →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Beiträgen
  incidentTitle: Ticket $NUMBER Details
  incidentDetails: Störungsdetails
  incidentFixed: Gelöst
  incidentOngoing: Fortlaufend
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: Ansehen und abbonieren auf GitHub
  incidentCommentSummary: Geschrieben am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Tickets
  pastIncidents: Vergangene Störungen
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS Beiträgen
  liveStatus: Live Status
  overallUptime: "Gesamte Verfügbarkeit: $UPTIME"
  overallUptimeTitle: Gesamte Verfügbarkeit
  averageResponseTime: "Durchschnittliche Reaktionszeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Reaktionszeit
  sevelDayResponseTime: 7-Tages-Reaktionszeit
  responseTimeMs: Reaktionszeit (ms)
  up: Up
  down: Down
  degraded: Eingeschränkt
  ms: ms
  loading: Lädt
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: Es ist ein Fehler aufgetreten
  errorIntro: Während des Aufrufs der neusten Statusdetails ist ein Fehler aufgetreten.
  errorText: Sie können es in ein paar Minuten noch einmal versuchen.
  errorHome: Zur Webseite
  pastScheduledMaintenance: Vergangene geplante Wartungen
  scheduledMaintenance: Geplante Wartungen
  scheduledMaintenanceSummaryStarted: Begonnen am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Begonnen am
  startsAt: Beginnt am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Erledigt
  incidentScheduled: Geplant
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: alle

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
